### ISSUE TITLE
use a different format for data on the wire

### ISSUE THREAD

**Issue by vivlim** [lifning/sync-or-sim#5]
ast.literal_eval is not very good, but this can wait until we have a clearer idea of everything we actually wanna send

**Comment by lifning** [comment]
batteries-included options...
[pickle](https://docs.python.org/3/library/pickle.html) somewhat efficient, built in to python, but vulnerable to arbitrary code execution (though no worse off than `ast.literal_eval` i bet)
[json](https://docs.python.org/3/library/json.html) less efficient text based format, i shudder to think about all the wrapping stuff in unicode/bytes conversions we'd have to do, but probably resistant to arb code exec
[struct](https://docs.python.org/3/library/struct.html) we could write our own binary format spec in this notation (i've done this a tiny bit in some of the py_retro audio code IIRC)

external stuff...
[capnproto](https://capnproto.org/) and [flatbuffers](https://github.com/google/flatbuffers) and [protobuf](https://github.com/google/protobuf) exist, but would introduce a dependency, an IDL, and something of a build step

**Comment by vivlim** [comment]
i tried json initially but no native support for bytes was a pain

**Comment by vivlim** [comment]
doublechecked and websockets can indeed send binary frames.

i'm kinda leaning towards struct. i want to build a slick visualizer in react eventually & keep most of that visual noise out of the emulator. there's a [npm package for packing and unpacking c structs](https://www.npmjs.com/package/c-struct) so we're good there.

**Comment by lifning** [comment]
this is https://github.com/lifning/sync-or-sim/pull/17
