### ISSUE TITLE
some way to declare which addr ranges are to be synced per game

### ISSUE THREAD

**Issue by vivlim** [lifning/sync-or-sim#7]
this should be able to express
* what the range is
* what the synchronization strategy should be, allowing for custom code
* optional: how to transform the data into something understandable (and printable)

**Comment by lifning** [comment]
a way to group ranges that should by synched together atomically (e.g. that
one byte of battle data that was hiding in the menu block should be part of
the same update message as the rest of the battle data)

**Comment by lifning** [comment]
(this was merged a week ago)
